### PR TITLE
Add support for s3:// and https:// protocols with some minor improvements.

### PR DESCRIPTION
**Pull request by janrotter**

### CODE REVIEW

**Comment by mikebryant** [comment]
I'm not convinced these changes are in-scope for nexus-configurator. It's designed to take a file of config and configure nexus. We shouldn't be trying to support arbitrary file sources - it's simple to gather the file from whatever source is necessary and then run this script.

**Comment by janrotter** [comment]
Could you please at least consider pulling the first two commits then? They bring some improvements that are unrelated to the s3:// and https:// support. I can create a new pull request with just these changes.

**Comment by stuart-warren** [comment]
if you could create a separate merge request that would be great, thanks!

**Comment by stuart-warren** [comment]
closing in favour of #7

**Pull request closed without merging**
